# Generated by Django 5.0.3 on 2024-04-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0002_alter_uploadedfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
    ]
